name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read   # Default read access for repository contents

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Check Azure CLI
      run: az --version

    - name: Print Working Directory
      run: pwd

    - name: List Files
      run: ls -la

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Terraform Init
      run: |
        cd .github
        terraform init

    - name: Terraform Plan
      run: |
        cd .github
        terraform plan -out=tfplan

    - name: Terraform Apply
      run: |
        cd .github
        terraform apply -auto-approve tfplan
